//Exports all handler functions
export * from "./mappings/avail";
export * from "./mappings/dock";
export * from "./mappings/joystream";
export * from "./mappings/polimec";
export * from "./mappings/polkadot";
export * from "./mappings/kusama";
export * from "./mappings/manta";
export * from "./mappings/moonbeam";
export * from "./mappings/moonriver";
export * from "./mappings/aleph-zero";
export * from "./mappings/turing";
export * from "./mappings/calamari";
export * from "./mappings/zeitgeist";
export * from "./mappings/polkadex";
export * from "./mappings/ternoa";
export * from "./mappings/westend";
export * from "./mappings/vara";
import "@polkadot/api-augment";
