name: PR check
on:
  pull_request:

jobs:
  pr:
    name: build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Load Node version
        id: versions
        run: |
          source versions.env
          echo "node=$NODE_VERSION" >> "$GITHUB_OUTPUT"
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.versions.outputs.node }}
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
